name: Docker Verify

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  docker-verify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t movie-sentiment:ci .

      - name: Run container
        run: |
          docker run -d --name movie_sentiment_ci \
            -p 8000:8000 \
            movie-sentiment:ci

      - name: Check container is running
        run: |
          sleep 3
          docker ps | grep movie_sentiment_ci

      - name: Cleanup
        if: always()
        run: docker rm -f movie_sentiment_ci || true